version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vehicles
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  vehicle-api:
    build: .
    container_name: vehicle-api
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/vehicles
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    volumes:
      - .:/app

volumes:
  mysql_data:
